name: Deploy on Render

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      - name: Run Tests
        run: pytest backend/tests
        env:
          DATABASE_URI: postgresql://test_user:test_password@localhost:5432/test_db

      - name: Trigger on Render
        if: success()
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"